export default {
	errorCode:{	
		"-1"	:"Unknown error",
		"-105"  : "Data does not exist",
		"-109"  : "Camera does not exist",
		"-110"  : "No face image in the library",
		"-113"  : "Username or password error",
		"-114"  : "User already exists",
		"-115"  : "The channel already has a camera",
		"-116"  : "The face image already exists",
		"-117"  : "The face library does not exist",
		"-118"  : "The number of face library has reached the limit",
		"-119"  : "The face library already exists",
		"-122"  : "The number of images has reached the limit",
		"-123"  : "The library has been bound to the camera, please untie it before deleting",
		"-126"	: "No such face image in the library",
		"-139"	: "Camera is not online",
		"-141"  : "Soory,you donnot have this permission",
		"-142"  : "Weak Level Passord",
		"-145"  : "当前用户密码输入有误", //1.2+
		"-146"  : "该角色下存在用户不可删除", //1.2+
		"-610"  : "Snap mode switch failed",
		"-1101" : "No face or multiple faces detected",
		"-1102" : "The face image quality is too low",
		"-1104" : "Incorrect image format or broken image",
		"-2100" : "No content to export",
		"-3596" : "Parameter input error",
		"-3599" : "'msg_id' error",
		"-3603"	: "Upgrade failed",
		"-3606" : "Network configuration error",
		"-3607" : "The current system is already in this mode",
		"-3608" : "Switch mode failed",
		"-3614" : "NTP server access error",
		"-3616" : "The crt or key file cannot be imported in HTTPS mode",
		"-3617" : "The crt or key file cannot be deleted in HTTPS mode",
		"-3619" : "Toggle https/http failed",
		"-3620" : "The capture strategy cannot be modified in Image mode",
		"-3624" : "System internal error, please try again",
		"-3625" : "crt or key file not yet imported",
	}	
}