export default {
	msgCode:{
                "257"               :"Log in",
                "258"               :"Log out",
                "260"               :"Request user list",
                "259"               :"Change password",
                "262"               :"Profile",
                "261"               :"Add user",
                "264"               :"Delete user",
                "263"               :"Edit user",
                "265"               :"Role list",
                "266"               :"Add role",
                "267"               :"Delete role",
                "268"               :"Modify role",
                "513"               :"Add camera",
                "514"               :"Delete camera",
                "515"               :"Modify camera",
                "516"               :"Query camera",
                "517"               :"Video playback",
                "518"               :"Change access mode",
                "519"               :"Query access mode",
                "520"               :"Query capture mode",
                "521"               :"Set capture mode",
                "522"               :"Get default effective area",
                "523"               :"Set maximum and minimum face resolutions",
                "524"               :"Get maximum and minimum face resolutions",
                "769"               :"Detect face in an image",
                "770"               :"Extract face features from an image",
                "771"               :"1:1 face compare",
                "772"               :"1:N face compare ",
                "773"               :"Extract face features from images",
                "1025"              :"Create target database",
                "1026"              :"Delete target database",
                "1027"              :"Modify target database",
                "1028"              :"Query target database",
                "1029"              :"Import an image ",
                "1030"              :"Import images ",
                "1031"              :"Delete an image from database",
                "1032"              :"Query face image in database",
                "1033"              :"Modify face image in database",
                "1034"              :"Query target database in paging mode",
                "1035"              :"Query images in source database in paging mode",
                "1036"              :"Query alarm images in paging mode",
                "1037"              :"Query snapshots in paging mode",
                "1038"              :"Export images from source database in paging mode",
                "1039"              :"Export alarm images in paging mode",
                "1040"              :"Export snapshots in paging mode",
                "1041"              :"Export selected images from source database",
                "1042"              :"Export selected alarm images",
                "1043"              :"Export selected snapshots",
                "1044"              :"Delete images from database",
                "1045"              :"Clear Records",
                "1281"              :"Get version information",
                "1282"              :"Set time",
                "1283"              :"Query time",
                "1284"              :"Save MQTT settings ",
                "1285"              :"Query MQTT settings",
                "1286"              :"Get push key",
                "1287"              :"Modify storage strategy",
                "1288"              :"Query storage strategy",
                "1289"              :"Set log level",
                "1290"              :"Configure NTP settings",
                "1291"              :"Query NTP settings",
                "1292"              :"Import software upgrade file ",
                "1293"              :"Software upgrade",
                "1294"              :"Restart services",
                "1295"              :"Default network adapter settings",
                "1296"              :"Configure network information",
                "1297"              :"Query network information",
                "1298"              :"Modify HTTP settings",
                "1299"              :"Query HTTP settings",
                "1309"              :"Modify Viper settings",
                "1308"              :"Query Viper settings",
                "1300"              :"Modify device ID",
                "1301"              :"Query device ID",
                "1304"              :"Query HTTPS file ",
                "1303"              :"Delete HTTPS file",
                "1302"              :"Upload HTTPS file",
                "1306"              :"Query current web protocol (HTTP or HTTPS)",
                "1305"              :"Configure current web protocol (HTTP or HTTPS)",
                "1307"              :"Get default language",
                "1312"              :"Query system logs", //1.1.3
                "1311"              :"Export system logs", //1.1.3
                "1317"              :"Restore system",
                "1331"              :"Export log files",//1.2
                "1318"              :"Query operation logs",//1.2
                "1319"              :"Query system logs",
                "1537"              :"Query relay",
                "1538"              :"Add relay",
                "1539"              :"Delete relay",

	}	
}