import enLocale from 'element-ui/lib/locale/lang/en'
import errorCode  from "./en-code"

export default {
  // element-ui
  ...enLocale,
    //errorCode
  ...errorCode,
    //标题
  logoTitel                    :"Intelligent Edge Device",
  //主菜单                       ",
  realTimeVideo                :"Live Preview",
  recordQuery                  :"Record Query", //1.2
  snapshotQuery                :"Capture Record Query",
  alarmQuery                   :"Alarm Record Query",
  faceService                  :"Face Service",  //1.2
  libraryManage                :"Target Database Management",
  oneToOne                     :"1:1 Comparison",  //1.2
  retrieval                    :"Image Retrieval",  // 1.2  
  //eventManage                  :"事件管理",  //1.2
  alarmRuleSet                 :"Alarm Pop-ups",  //1.2
  //signalLinkage                :"信号联动管理",  //1.2
  //userManage                   :"用户管理", //1.2
  sysSettings                  :"System Settings",
  generalSettings              :"General Settings",
  networkSettings              :"Network Settings",
  deviceManage                 :"Device Management",
  sysInfo                      :"System Information",
  storageManage                :"Storage Management",
  interfaceProtocol            :"Interface Protocol",
  //logs                         :"系统日志", //1.2
  //advancedSet                  :"高级设置", //1.2
  languge                      :"Language",
  login                        :"Login",
  logout                       :"Logout",
  //导出                         ",
  totalNumTip                  :"You can export up to {num} records at a time",
  curNumTip                    :"Current total records: {num}",
  batchExport                  :"Batch Export",
  exportInterval               :"Export quantity range",
  startExport                  :"Start",
  endExport                    :"End",
  //通用                         ",
  submitTag                    :"OK",
  exportAllTag                 :"Export all",
  filterCondition              :"Filter by",
  exportTag                    :"Export",
  seqNumber                    :"ID",
  operation                    :"Operation",
  showDetail                   :"View Details",
  allTip                       :"All",
  showDetailOne                :"View",
  default                      :"Default",
  flush                        :"Refresh",
  cancel                       :"Cancel",
  delete                       :"Delete",
  edit                         :"Edit",
  reset                        :"Reset",
  close                        :"Close",
  startDate                    :"Start Date",
  endDate                      :"End Date",
  similarity                   :"Similarity",
  time                         :"Time",
  hint                         :"Tips",
  details                      :"Details",
  settingSuccess               :"OK",
  faceLead                     :"Image Import",
  confDelete                   :"Delete",
  deleteOk                     :"OK",
  deleteError                  :"Failed to delete ",
  //file                         ",
  chooseFile                   :"Select Files",
  fileHint                     :"Please confirm that the current export file has been downloaded. After closing, you will need to export again. Continue?",
  fileErrHint                  :"Uploading an image failed, re-upload?",
  uploadSuccess                :"Image uploaded successfully",
  putInSuccNumber              :"Successes",
  putInErrNumber               :"Failures",
  uploadAgain                  :"Re-upload",
  //实时预览                     ",
  realTimeVideoTag             :"Live Stream",
  oneSplitScreen               :"One Screen",
  fourSplitScreen              :"Quad Screen",
  eightSplitScreen             :"Octuple Screen",
  autoMaticAlarm               :"Automatic Alarm Pop-ups",
  captureInfo                  :"Capture Info",
  //抓拍记录                     ",
  captureTitle                 :"Capture Details",
  allChannel                   :"All Channels",
  captureFigure                :"Images",
  channelNumber                :"Channel No.",
  channelName                  :"Name",
  captureDate                  :"Time",
  //common                       ",
  warnTitle                    :"Alarm Details",
  capturingFace                :"Capture Face Image",
  compareFace                  :"Compare Face Image",
  faceIdent                    :"Identity",
  uoloadForCompare             :"Upload face image to compare",
  uploadForSearch              :"Upload face image to search",
  reUploadSearch               :"Click image to re-upload",
  //告警记录                     ",
  libraryNameTip               :"Target Database",
  libraryAttrTip               :"Database Attribute",
  allLibrary                   :"All Target Databases",
  allLibraryAttr               :"All Database Types",
  blackLibType                 :"Blacklist Database",
  writeLibType                 :"Whitelist Database",
  //目标库                       ",
  libraryNameRe                :"Enter database name",
  libraryName                  :"Name",
  pictureTotal                 :"Total",
  libCrateTime                 :"Creation Time",
  libraryTypeTag               :"Type",
  addLibrary                   :"Add target database",
  editLibrary                  :"Edit target database",
  //人脸库                       ",
  face_picTag                  :"Image",
  face_nameTag                 :"Name",
  face_ageTag                  :"Age",
  face_sexTag                  :"Gender",
  face_ident                   :"Identity No.",
  //人脸库-新增                  ",
  face_rl_addTitle             :"Add target source",
  //人脸库-编辑                  ",
  face_rl_eidtTitle            :"Edit personnel info",
  //人脸库-详情                  ",
  face_rl_infoTitle            :"Personnel Details",
  face_rl_delete               :"Delete",
  face_rl_edit                 :"Edit attribute",
  //删除                         ",
  face_noChoose                :"You haven't selected a record",
  face_onlyDelete              :"You can delete up to 50 records",
  face_batchDelete             :"You are deleting {num} records, continue?",
  face_deleteTitle             :"This operation will permanently delete the personnel details, continue?",
  face_affi_delete             :"Delete personnel details",
  //系统设置                     ",
  //常规设置                     ",
  sys_cg_dateFormat            :"Date Format",
  sys_cg_timeFormat            :"Time Format",
  sys_cg_timeZone              :"Time Zone",
  sys_cg_sysTime               :"System Time",
  sys_cg_ntpsetting            :"NTP Settings",
  sys_cg_nptserver             :"NTP Server",
  sys_cg_port                  :"Port",
  sys_cg_updateInv             :"Update Cycle (mins): ",
  sys_cg_using                 :"Enable",
  sys_cg_noUsing               :"Disable",
  //网络设置                     ",
  sys_wl_netInter              :"Network Port",
  sys_wl_autoGet               :"DHCP",
  sys_wl_ipAddr                :"IP Address",
  sys_wl_subNet                :"Subnet Mask",
  sys_wl_gateway               :"Gateway",
  sys_wl_macAddr               :"MAC Address",
  sys_wl_dnsServer             :"DNS Server",
  sys_wl_dnsGetFun             :"DNS Setup",
  sys_wl_dnsAutoGet            :"Automatic",
  sys_wl_dnsMyGet              :"Manual",
  sys_wl_firstDNS              :"Primary",
  sys_wl_backDNS               :"Secondary",
  sys_wl_defutNet              :"Default NIC",
  sys_wl_useThisNet            :"Network Port",
  /////编辑                      ",
  sys_wl_title                 :"Edit Network Port",
  sys_wl_mode                  :"Mode",
  sys_wl_mode_static           :"Static",
  sys_wl_mode_dhcp             :"DHCP",
  sys_wl_IpVersion             :"IP Version",
  sys_wl_addr                  :"Address",
  //设备管理                     ",
  sys_equ_mode                 :"Access Mode",
  sys_equ_video                :"Video",
  sys_equ_strategy             :"Capture Strategy",
  sys_equ_image                :"Image",
  sys_equ_deepImage            :"Capture",
  sys_equ_addEqu               :"Add Device",
  sys_equ_chan                 :"Channel",
  sys_equ_chanNum              :"Channel No.",
  sys_equ_chanName             :"Name",
  sys_equ_ipOrDomain           :"IP/Domain",
  sys_equ_equType              :"Device Type",
  sys_equ_protocol             :"Protocol",
  sys_equ_port                 :"Port",
  sys_equ_onlineStat           :"Status",
  sys_equ_isOnline             :"Online",
  sys_equ_noOnline             :"Offline",
  sys_equ_clMod_jz             :"Accurate",
  sys_equ_clMod_ds             :"Timing",
  sys_equ_clMod_ss             :"Live",
  sys_equ_imgMode1             :"Capture Camera",
  sys_equ_imgMode2             :"IP Camera",
  ////添加&修改&查看             ",
  sys_equ_title_show           :"Device Details",
  sys_equ_title_edit           :"Edit Device",
  sys_equ_title_dele           :"Delete Device",
  sys_equ_delete               :"This operation will permanently delete this device, continue?",
  sys_equ_deleteErr            :"No free channel for more devices",
  sys_equ_deleteOk             :"The device is deleted",
  sys_equ_libTag               :"Target Database",
  sys_equ_threshold            :"Threshold (%)",
  sys_equ_userName             :"Username",
  sys_equ_password             :"Password",
  sys_equ_codeStream           :"Data Rate",
  sys_equ_ipAddr               :"IP Address",
  sys_equ_equAddr              :"Camera Position",
  //热区绘制                     ",
  hotToDraw_title              :"ROI",
  //系统信息                     ",
  sys_info_version             :"Version Information",
  sys_info_productEq           :"Serial Number",
  sys_info_sysVer              :"System Version",
  sys_info_webVer              :"WEB Version",
  sys_info_anthor              :"Others",
  sys_info_sysReboot           :"System Restart",
  sys_info_reboot              :"Restart",

  //system_resource              : "系统资源",
  //cpu_usage                    : "CPU 使用率",
  //memory_usage                 : "内存使用率",
  
  //存储管理                     ",
  sys_save_setting             :"Storage Settings",
  sys_save_all                 :"Total (MB)",
  sys_save_residue             :"Free (MB)",
  sys_save_plan                :"Storage Plan",
  sys_save_strategy            :"Storage Strategy",
  sys_save_fullCover           :"Refill",
  sys_save_fullStop            :"Freeze",
  //接口协议                     ",
  sys_api_equId                :"Device ID",
  sys_api_produce              :"Access Protocol",
  sys_api_mqttPort             :"mqtt Port",
  sys_api_mqttName             :"mqtt Username",
  sys_api_mqttPwd              :"mqtt Password",
  sys_api_title                :"HTTP Configuration",
  //输入提示                     ",
  inputError                   :"There are still empty fields",
  //placehor                     ",
  choose                       :"Select",
  inputLibName                 :"Enter database name",
  inputIDOrName                :"Enter name",
  inputTime                    :"Select system time",
  inputName                    :"Enter name",
  inputAge                     :"Enter age",
  inputIdent                   :"Enter identity No.",
  inputAddr                    :"Enter address",
  chooseDateTime               :"Select date and time",
  ///login                       ",
  inputUserName                :"Enter username",
  inputUserPwd                 :"Enter password",
  //http                         ",
  inputDeviceId                :"The device ID cannot be empty",
  inputHttpUrl                 :"http_url cannot be empty",
  inputHttpKey                 :"http_key cannot be empty",
  //err                          ",
  libNameErr                   :"The database name cannot be empty",
  libTypeErr                   :"No database type selected",
  ageErr                       :"Fill in the correct age",
  imageErr                     :"Upload a face image",
  sysTimeErr                   :"The system time cannot be empty or the format is incorrect!",
  mqttPortNullErr              :"The mqtt port cannot be empty",
  mqttPortErr                  :"The mqtt port does not match the format (0-65535)",
  mqttTopicErr                 :"Mqtt_topic cannot be empty",
  mqttIpErr                    :"Mqtt_ip cannot be empty",
  mqttNameErr                  :"The username of mqtt cannot be empty",
  mqttPwdErr                   :"The password of mqtt cannot be empty",
  //confirm                      ",
  changeModeWarn               :"After confirming, the system will clear the current cameras and restart the service. Are you sure to confirm?",
  changeModeTitle              :"Switch access mode",
  changeModeSucc               :"Access mode changed successfully! Please refresh the page in 20s and log in to the system again",
  changeCLTip                  :"Do you want to switch to the {type} strategy?",
  changeCLSucc                 :"Capture strategy changed successfully",
  mqttCloseSucc                :"MQTT closed successfully. Please log in again in 25s...",
  mqttUpdateSucc               :"MQTT configuration information modified successfully. Please log in again in 25s...",
  httpUpdateSucc               :"HTTP configuration information modified successfully. Please log in again in 25s...",
  //下载页面                     ",
  download_src                 :"Download Link",
  clickDownload                :"Click to download for details",
  saveSuccess                  :"Saved",
  updateSuccess                :"Modified",
                               
  //补缺                       
  onLibrary                    :"Database",
  deleteLibrayTip              :"This operation will permanently delete this target database, continue?",
  deleteLibTitle               :"Delete Target Database",
  libraryMaxNumErr             :"The number of the target databases has reached the limit",
  addOk                        :"Added",
  updateOk                     :"Modified",
  addTip                       :"Add",
  targetSearchTip              :"Enter keyword",
  addNewFaceInfo               :"Add target",
  chooseFolder                 :"Select a folder",
  batchDelete                  :"Bulk deletion",
  sureDelete                   :"OK",
  saveTip                      :"Save",
  sex_hanzi                    :"Male",
  sex_meizi                    :"Female",
  idCardNumber                 :"Identity No.",
                               
  cancelUpdate                 :"Cancel",
  saveUpdate                   :"Save",
  makeSure                     :"Confirm",
  makeSure2                    :"OK",
  faceMakeSureLoad             :"Please confirm that the file of current face import details has been downloaded. After closing, you can no longer download this file, continue?",
                               
  emptyData                    :"No data yet",
                               
  loginNameNull                :"The username cannot be empty",
  loginPwdNull                 :"The password cannot be empty",
                               
  TimeTo                       :"to",
                               
  noSupportVideo               :"In image mode, live video is not supported",
                               
  softUpdate                   :"Software Upgrade",
  loadUpdatePackage            :"Import upgrade file",
  clickLoadUpdate              :"Select upgrade file",
  softUpdateTip                :"This operation will upgrade the software, continue?",
  softUpdateSuccess            :"Software upgrade is successful! Please refresh the page in 20s and log in to the system again",
  noChooseUpdateFile           :"You haven't selected an upgrade file yet",
  rebootTip                    :"This operation will restart the device, continue?",
  rebootTitle                  :"Restart",
  rebootSuccess                :"The device will be restarted. Please log in again in about 25s…",
                               
  export                       :"Import",
  upgrade                      :"Upgrade",
                               
  flag_yes                     :"Yes",
  flag_no                      :"No",
                               
  DNSSetErr                    :"Incorrect DNS format",
                               
  ipAddrNull                   :"The IP address cannot be empty",
  subNetNull                   :"The subnet mask cannot be empty",
  netWayNull                   :"The gateway cannot be empty",
                               
  dataTimeTitle                :"Date Time",
                               
  hourFomat                    :"Hour System",
  noChooseChannel              :"The channel has not been selected",
  channelNameNull              :"The channel name cannot be empty",
  protocolNull                 :"The protocol has not been selected",
                               
  RTSPAddressNull              :"The RTSP address cannot be empty",
  IPAddressNull                :"The IP address cannot be empty",
  IPAddressErr                 :"Incorrect IP address format",
  portNotNull                  :"The port cannot be empty",
                               
  inputInteger                 :"Please enter an integer value",
  inputPort                    :"The port numbers range from 0 to 65535",
                               
  chooseLibrary                :"Select target database",
                               
  threshold                    :"Threshold",
  thresholdNotNull             :"The threshold cannot be empty",
  libFaceIsNull                :"No target database",
                               
  updateBtn                    :"Modify",
                               
  y_m_d                        :"Year-month-day",
  m_d_y                        :"Month-day-year",
  d_m_y                        :"Day-month-year",
                               
  pleChooseChannel             :"Please select a channel",
                               
  //https设置                  
  httpsSettingMenu             :"Security Settings",
  httpsSettingTitle            :"HTTPS Security Settings",
  isUsingHttps                 :"ON/OFF",
  https_start                  :"On",
  https_unInstall              :"Uninstall",
  https_upload                 :"Upload",
  https_cert_hp                :"Click Import to select an SSL certificate",
  https_key_hp                 :"Click Import to select an SSL key",
  https_load_cert              :"Import Crt",
  https_cur_cert               :"Current Crt",
  https_cur_key                :"Current Key",
  https_load_key               :"Import Key",
                               
  //Flash相关                  
  enableFlashTitle             :"Install or enable the Flash Player",
  enableFlashTips              :"The current feature requires Flash Player support, please install or enable it first",
                               
  confirmChangeMQTTStatusTitle :"Toggle Access Protocol",
  confirmChangeMQTTStatusTips  :"Please be careful! Toggling the access protocol will delete all data, continue?",

  https_key_no_choose          : "SSL key file not yet selected",
  https_crt_no_choose          : "SSL certificate file not yet selected",

   //设备管理补缺
  changeModeCl                 : "Modify capture strategy",
  Accurate                     : "Accurate",
  Timing                       : "Timing",
  RealTime                     : "Live",

  drawAreaMsg                  : "The length or width of ROI cannot be less than 60px",

  networkError                 : "Network Error",
  manage                       : "Manage",
  notNull                      : "The {name} cannot be empty",
  valueErr                     : "Incorrect {name} format",
  uploadOk                     : "Uploaded",
  unInstallOk                  : "Uninstalled",
  
  //1:N人脸对比
  faceCtra_titComp             : "1:N Comparison",
  faceCtra_grade               : "Rating Reference",
  faceCtra_frist               : "0 ~ 60%: The two images are probably not the same person;",
  faceCtra_second              : "60% ~ 85%: The two images might be the same person;",
  faceCtra_third               : "85% ~ 100%: The two images are most likely the same person!",

  // M:N 对比
  retri_tit                    : "Compare",
  retri_getResult              : "TOP-N",
  compare_libary               :"Please select the target database to search",

  // 1.2.1
  interface_protocol_conf      :"Interface Protocol Settings",
  alarmRule_blacklist          :"Blacklist",
  alarmRule_whitelist          :"Whitelist",
  alarmRule_stranger           :"Stranger",

  // // 库管理
  // lib_custom_max_error         :"自定义属性最多五个",
  // minimum_face_pix_setting     :"最小人脸像素设置",
  // detection_frame_rate         :"检测帧率",
  // // 用户管理
  // user_info                    :"用户",
  // user_role                    :"角色",
  // user_onLineOr                :"用户在线状态",
  // edit_password                :"修改密码",
  // input_newPwd                 :"新密码",
  // plInput_newPwd               :"请输入新密码",
  // plInput_en_newPwd            :"请确认密码",
  // ensure_newPwd                :"确认密码",
  // pwd_inconsistency            :"两次密码输入不一致",
  // reset_password               :"重置密码",
  // // 系统日志
  // logs_edit_content            :"操作内容",
  // logs_edit_person             :"操作人",
  // logsQuery                    :"查询",

  inputViperUrl                 : "url",
  inputViperUrlErr              : "The url cannot be empty",
  inputViperKey                 : "Enable",
  inputViperSwitch              : "key",
  inputViperKeyErr              : "The key cannot be empty",
  http_url                      : "http_url",
  http_key                      : "http_key",
  
};
